-- ==========================================================
-- QRION Admin Panel — tabel Artikel (CRUD ala WordPress)
-- Jalankan sekali di Supabase SQL Editor.
-- ==========================================================

create table if not exists public.articles (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  title         text not null,
  excerpt       text not null default '',
  category      text not null default 'Artikel',
  iso_date      date not null default current_date,
  image         text,                    -- gambar utama (URL, boleh null)
  source_url    text not null default '',
  status        text not null default 'draft'
                check (status in ('draft', 'published', 'scheduled')),
  published_at  timestamptz,             -- jadwal tayang (opsional)
  content       text not null default '<p></p>',  -- HTML hasil editor Tiptap
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz              -- non-null = di Sampah
);

create index if not exists articles_status_date_idx
  on public.articles (status, iso_date desc);
create index if not exists articles_deleted_idx
  on public.articles (deleted_at);

-- RLS aktif tanpa policy: hanya service role (SUPABASE_SECRET_KEY) yang bisa akses
alter table public.articles enable row level security;

-- Tabel pertama diisi otomatis oleh aplikasi (auto-seed 38 artikel dari kode)
-- saat halaman /admin/artikel pertama dibuka. Tidak perlu insert manual.
